# docker-compose.yml для Telegram Sentiment Bot (опционально)
version: '3.8'

services:
  bot:
    build: .
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./logs:/app/logs
    restart: unless-stopped